// Download self-hosted woff2 for Fraunces (display) + Inter (text) from Google Fonts
// and emit fonts/fonts.css with local @font-face rules. Idempotent.
//
//   node scripts/fetch-fonts.mjs
//
// Self-hosting removes the third-party Google Fonts dependency (production-hardening)
// and makes local previews render in the real typefaces.
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

// Weight/style sets that the site actually uses.
const FAMILIES = [
  'Inter:wght@300;400;500;600;700',
  'Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,600;1,9..144,300;1,9..144,400',
];

const outDir = resolve('fonts');
mkdirSync(outDir, { recursive: true });

const url =
  'https://fonts.googleapis.com/css2?' +
  FAMILIES.map((f) => 'family=' + encodeURIComponent(f)).join('&') +
  '&display=swap';

const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

// Split into @font-face blocks and rewrite each gstatic woff2 to a local file.
const blocks = css.split('@font-face').slice(1);
let out = '/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs */\n';
let count = 0;
const seen = new Set();
for (const raw of blocks) {
  const block = '@font-face' + raw.slice(0, raw.indexOf('}') + 1);
  const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
  const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1] || '400';
  const style = /font-style:\s*italic/.test(block) ? 'italic' : 'normal';
  const src = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
  if (!fam || !src) continue;
  const name = `${fam.replace(/\s+/g, '')}-${weight}-${style}.woff2`.toLowerCase();
  if (seen.has(name)) continue;
  seen.add(name);
  const bin = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(resolve(outDir, name), bin);
  out += block.replace(/src:\s*url\([^)]+\)/, `src: url('${name}')`) + '\n';
  count++;
}
writeFileSync(resolve(outDir, 'fonts.css'), out);
console.log(`fetched ${count} font files -> fonts/`);
